title: "Tamanna Kumavat"
description: "Master’s Student in AI & Data Science • Full-Stack Developer • AI & Data Science Expert"
url: "https://tamannakumavat.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

header_pages:
  - about.md
  - projects.md

author:
  name: "Tamanna Kumavat"
  avatar: "/assets/img/profilephoto.jpg"
  bio: "Master’s student in AI and Data Science at the University of Zurich with 7 years of full-stack development experience, focusing on LLMs, NLP, and model evaluation."
  location: "Zurich, Switzerland"
  links:
    - label: "GitHub"
      url: "https://github.com/tamannaKumavat"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/tamanna-kumavat/"
    - label: "Email"
      url: "mailto:tamanna_kumavat@outlook.com"

theme_skin: "default"
search: true
